name: fastqwiper
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.7.3
  - amply=0.1.4
  - appdirs=1.4.4
  - async-timeout=3.0.1
  - attrs=20.3.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - boto3=1.16.44
  - botocore=1.19.44
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.8
  - cachetools=4.2.0
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - coincbc=2.10.5
  - colorama=0.4.4
  - configargparse=1.2.3
  - cryptography=3.3.1
  - datrie=0.8.2
  - decorator=4.4.2
  - docutils=0.16
  - dropbox=10.10.0
  - expat=2.2.10
  - fftw=3.3.9
  - filechunkio=1.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - ftputil=4.0.0
  - gdk-pixbuf=2.42.2
  - gettext=0.19.8.1
  - ghostscript=9.53.3
  - giflib=5.2.1
  - gitdb=4.0.5
  - gitpython=3.1.11
  - glib=2.66.4
  - google-api-core=1.22.4
  - google-api-python-client=1.12.8
  - google-auth=1.24.0
  - google-auth-httplib2=0.0.4
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.31.2
  - google-crc32c=1.1.0
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - graphite2=1.3.14
  - graphviz=2.42.3
  - grpcio=1.34.0
  - harfbuzz=2.7.3
  - httplib2=0.18.1
  - icu=68.1
  - idna=2.10
  - imagemagick=7.0.10_28
  - importlib-metadata=3.3.0
  - importlib_metadata=3.3.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_core=4.7.0
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.4
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - librsvg=2.50.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - multidict=5.1.0
  - nbformat=5.0.8
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.4
  - oauth2client=4.1.3
  - openjpeg=2.3.1
  - openssl=1.1.1i
  - pandas=1.2.0
  - pango=1.42.4
  - paramiko=2.7.2
  - pcre=8.44
  - perl=5.26.2
  - pip=20.3.3
  - pixman=0.40.0
  - pkg-config=0.29.2
  - prettytable=2.0.0
  - protobuf=3.14.0
  - psutil=5.8.0
  - pulp=2.3.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.7.3
  - pygraphviz=1.6
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.9.1
  - python-dateutil=2.8.1
  - python-irodsclient=0.8.2
  - python_abi=3.9
  - pytz=2020.5
  - pyyaml=5.3.1
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.25.1
  - rsa=4.6
  - s3transfer=0.3.3
  - setuptools=51.0.0
  - simplejson=3.17.2
  - six=1.15.0
  - slacker=0.14.0
  - smmap=3.0.4
  - snakemake=5.31.1
  - snakemake-minimal=5.31.1
  - sqlite=3.34.0
  - tk=8.6.10
  - toposort=1.6
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2020e
  - uritemplate=3.0.1
  - urllib3=1.26.2
  - wcwidth=0.2.5
  - wheel=0.36.2
  - wrapt=1.12.1
  - xmlrunner=1.7.7
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
