{% set data = load_file_data('versions.json') %}
{% set version = data.get('wipertools') %}
{% set sha256 = "593e302ccfc1db5e7e1d5256a04782b31d095c659440ae8a82c9e25ae6313e9d" %}

package:
  name: wipertools
  version: {{ version }}

#app:
#  icon: icon_64x64.png

source:
  # git_url: https://github.com/mazzalab/fastqwiper.git
  path: ../
  # url: https://github.com/mazzalab/fastqwiper/archive/refs/tags/2024_11.zip
  # sha256: {{ sha256 }}

build:
  # number: { { environ.get('GITHUB_RUN_NUMBER', 0) } }
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('wipertools', max_pin="x.x") }}
  entry_points:
    - wipertools = wipertools.main:main
  script_env:
    - WIPERTOOLS_VERSION={{version}}

requirements:
  host:
    - python >=3.10
    - setuptools >=75.3
  run:
    - python >=3.10

test:
  imports:
    - wipertools
  commands:
    - wipertools --help

about:
  home: https://github.com/mazzalab/fastqwiper
  summary: A suite of programs that drop or fix pesky lines in FASTQ files and that split or merge FASTQ chunk files.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mazzalab
    - irongraft
