package:
  name: wipertools
  version: {{ wipertools_version }}

#app:
#  icon: icon_64x64.png

source:
  # git_url: https://github.com/mazzalab/fastqwiper.git
  path: ./

build:
  # number: { { environ.get('GITHUB_RUN_NUMBER', 0) } }
  number: 0
  noarch: python
  # script: python -m pip install --no-deps --ignore-installed .
  run_exports:
    - {{ pin_subpackage('wipertools', max_pin="x.x") }}
  entry_points:
    - wipertools = fastqwiper.wipertools:main

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - fastqwiper
  commands:
    - wipertools --help

about:
  home: https://github.com/mazzalab/fastqwiper
  summary: A suite of programs that drop or fix pesky lines in FASTQ files and that split or merge FASTQ chunk files.
  license: CC-BY-NC-ND-4.0
  license_family: CC
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mazzalab
