{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: fastqwiper
  version: {{ data.get('version') }}

#app:
#  icon: icon_64x64.png
  
source:
  git_url: https://github.com/mazzalab/fastqwiper.git

build:
  # number: 0
  number: {{ environ.get('GITHUB_RUN_NUMBER', 0) }}
  script_env:
      - GITHUB_RUN_NUMBER
  entry_points:
    - fastqwiper = fastq_wiper.wiper:wipe_fastq
 
requirements:
  build:
    - anaconda-client
    - conda-build    

  host:
    - python
    - numpy
    
  run:
    - python
    - colorama
    - click

test:
  imports:
    - fastq_wiper
  commands:
    - fastqwiper --help
    
about:
  home: https://github.com/mazzalab/fastqwiper
  summary: A package to wipe out uncompliant reads from FASTQ files
  license: MIT
  license_file: LICENSE.txt
