package:
  name: fastqwiper
  version: { { fastqwiper_version } }

#app:
#  icon: icon_64x64.png

source:
  git_url: https://github.com/mazzalab/fastqwiper.git

build:
  number: { { environ.get('GITHUB_RUN_NUMBER', 0) } }
  script_env:
    - RELEASE_VER
  entry_points:
    - wipertools = fastqwiper.wipertools:main

requirements:
  build:
    - python
    - numpy

  host:
    - python
    - numpy

  run:
    - python

test:
  imports:
    - fastqwiper
  commands:
    - wipertools --help

about:
  home: https://github.com/mazzalab/fastqwiper
  summary: An ensemble method to recover corrupted FASTQ files, drop or fix pesky lines, remove unpaired reads, and fix reads interleaving
  license: MIT
  license_file: LICENSE.txt
