{% set data = load_file_data('versions.json') %}
{% set version = data.get('wipertools') %}
{% set sha256 = "898812fc8d2ac86f22f4da9e24eb707383a681c8553aa6813a05b108c8e10582" %}

package:
  name: wipertools
  version: {{ version }}

#app:
#  icon: icon_64x64.png

source:
  # git_url: https://github.com/mazzalab/fastqwiper.git
  path: ../
  # url: https://github.com/mazzalab/fastqwiper/archive/refs/tags/2024_11.zip
  # sha256: {{ sha256 }}

build:
  # number: { { environ.get('GITHUB_RUN_NUMBER', 0) } }
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('wipertools', max_pin="x.x") }}
  entry_points:
    - wipertools = fastqwiper.wipertools:main
  script_env:
    - WIPERTOOLS_VERSION={{version}}

requirements:
  host:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - fastqwiper
  commands:
    - wipertools --help

about:
  home: https://github.com/mazzalab/fastqwiper
  summary: A suite of programs that drop or fix pesky lines in FASTQ files and that split or merge FASTQ chunk files.
  license: CC-BY-NC-ND-4.0
  license_family: CC
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mazzalab
    - irongraft
