name: Build and Deploy all

on: [push]

jobs:
  Docker:
    name: Docker CI
    uses: ./.github/workflows/docker_reusable.yml
    with:
        package_version: ${{vars.FASTQWIPER_VER}}${{github.run_number}}
    secrets:
        dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  Pypi:
    name: Pypi CI
    uses: ./.github/workflows/pypi_reusable.yml
    with:
        package_version: ${{vars.FASTQWIPER_VER}}${{github.run_number}}
    secrets:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        
  Conda:
    name: Conda CI
    uses: ./.github/workflows/conda_reusable.yml
    with:
        package_version: ${{vars.FASTQWIPER_VER}}${{github.run_number}}
    secrets:
        conda_token: ${{ secrets.CONDA_TOKEN }}