name: Test code

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest]  # , macos-latest, windows-latest

    env:
        OS: ${{ matrix.os }}
        PYTHON: '3.10'

    name: Test FastqWiper
    steps:
    - uses: actions/checkout@v1
      name: Clone repository
    
    - name: Install Miniconda (Mambaforge)
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          auto-activate-base: true
          show-channel-urls: true
          channels: conda-forge,defaults
          python-version: ${{ env.PYTHON }}
          environment-file: environment.yml
          miniforge-variant: Mambaforge
      
    - name: Run tests and collect coverage
      shell: bash -el {0}
      run: pytest --pyargs fastq_wiper --cov

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,PYTHON
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: pytest # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)