name: Conda

on: 
  workflow_call:
    inputs:
      package_version:
        required: true
        type: string
    secrets:
      conda_token:
        required: true

jobs:
  build-linux:
    name: Build (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["windows-latest", "ubuntu-latest"]  # , "macos-latest"", 
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Miniconda (Mambaforge)
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          show-channel-urls: true
          channels: conda-forge,defaults
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          
      - name: Installing Conda packages
        shell: bash -el {0}
        run: |
          mamba install -c conda-forge setuptools twine wheel boa anaconda-client conda-verify --yes --quiet
          conda env config vars set RELEASE_VER=${{ inputs.package_version }}

      - name: Building package (all OS)
        shell: bash -el {0}
        run: |
          conda mambabuild --quiet -c bfxcss -c conda-forge conda-recipe --python=${{ matrix.python-version }} --output-folder conda_dist
          
      - name: Convert the built package from Linux to MacOS
        shell: bash -el {0}
        run: |
          conda convert --platform osx-64 ./conda_dist/linux-64/*.tar.bz2 -o ./conda_dist
        if: matrix.os == 'ubuntu-latest'

      - name: Publishing package
        shell: bash -el {0}
        run: |
          anaconda -t ${{ secrets.conda_token }} upload -u bfxcss ./conda_dist/**/*.tar.bz2
