name: Pypi build

on: [push]

jobs:
    build-linux:
        name: Build (Python ${{ matrix.python-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
          max-parallel: 5
          matrix:
            os: ["ubuntu-latest"]  # ,"windows-latest", "macos-latest"
            python-version: ["3.10"]  # , "2.7"
    
        steps:
            - name: Install Miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                auto-activate-base: true
                show-channel-urls: true
                channels: defaults
                python-version: ${{ matrix.python-version }}
            
            - uses: actions/checkout@v3
              with:
                fetch-depth: 

            - name: Installing Conda packages
              shell: bash -el {0}
              run: conda install -c conda-forge setuptools twine wheel --yes --quiet
                    
            - name: Package build
              shell: bash -el {0}
              run: python setup.py build

            - name: Wheel creation
              shell: bash -el {0}
              run: python setup.py sdist bdist_wheel -d pypi_dist clean --all

            - name: Publishing package
              shell: bash -el {0}
              run: twine upload ./pypi_dist/*.whl -u __token__ -p %PYPI_TOKEN%