name: Conda build

on: [push]

jobs:
  build-linux:
    name: Build (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["ubuntu-latest"]  # , "macos-latest", "windows-latest"
        python-version: ["3.10"]  # , "2.7"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          show-channel-urls: true
          channels: conda-forge,defaults
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          
      - name: Installing Conda packages
        # shell: bash -el {0}
        run: conda install -c conda-forge setuptools twine wheel conda-build anaconda-client conda-verify --yes --quiet

      - name: Building package
        shell: bash -el {0}
        run: |
          conda build --quiet -c bfxcss -c conda-forge conda-recipe --python=${{ matrix.python-version }} --output-folder conda_dist
          conda convert --platform win-64 .conda_dist/linux-64/*.tar.bz2 -o ./conda_dist
          conda convert --platform osx-64 .conda_dist/linux-64/*.tar.bz2 -o ./conda_dist
          ls -lR conda_dist