name: Conda

on: [push]

jobs:
  build-linux:
    name: Build (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["ubuntu-latest", "windows-latest"]  # , "macos-latest"
        python-version: ["3.10"]  # , "3.9", "3.8", "3.7"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          show-channel-urls: true
          channels: conda-forge,defaults
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          
      - name: Installing Conda packages
        shell: bash -el {0}
        run: conda install -c conda-forge setuptools twine wheel conda-build anaconda-client conda-verify --yes --quiet

      - name: Building package for Linux&MacOS
        shell: bash -el {0}
        run: |
          conda build --quiet -c bfxcss -c conda-forge conda-recipe --python=${{ matrix.python-version }} --output-folder conda_dist
          conda convert --platform osx-64 ./conda_dist/linux-64/*.tar.bz2 -o ./conda_dist
        if: matrix.os == 'ubuntu-latest'

      - name: Building package for Windows only
        shell: bash -el {0}
        run: |
          conda build --quiet -c bfxcss -c conda-forge conda-recipe --python=${{ matrix.python-version }} --output-folder conda_dist
        if: matrix.os == 'windows-latest'

      - name: Publishing package
        shell: bash -el {0}
        run: |
          anaconda -t ${{ secrets.CONDA_TOKEN }} upload -u bfxcss ./conda_dist/**/*.tar.bz2