name: Packaging and Delivery to Conda

on: [push]

jobs:
  build-linux:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["ubuntu-latest"]  # , "macos-latest", "windows-latest"
        python-version: ["3.11"]  # , "2.7"

    steps:
      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}
          prefix: 2023.

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          show-channel-urls: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml    # Path to the build conda environment
          

      # - name: Conda initialization
      #   shell: bash -el {0}
      #   run: |
      #     conda config --set always_yes yes --set changeps1 no
      #     conda config --set show_channel_urls true
      #     conda config --add channels conda-forge
      #     conda install -c conda-forge setuptools twine wheel conda-build anaconda-client conda-verify --yes --quiet

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: conda-build
          python-version: ${{ matrix.python-version }}
          platform_linux-64: true
          platform_osx-64: false
          platform_win-64: false
          user: bfxcss
          label: auto
          token: ${{ secrets.CONDA_TOKEN }} # Replace with the right name of your secret

    # steps:
    # - uses: actions/checkout@v3
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.10'
    # - name: Add conda to system path
    #   run: |
    #     # $CONDA is an environment variable pointing to the root of the miniconda directory
    #     echo $CONDA/bin >> $GITHUB_PATH
    # - name: Install dependencies
    #   run: |
    #     conda env update --file environment.yml --name base
    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     conda install pytest
    #     pytest
