name: Singularity

on: 
  workflow_call:
    inputs:
      package_version:
        required: true
        type: string
    secrets:
      sylabs_token:
        required: true

jobs:
  docker_build_publish:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: eWaterCycle/setup-singularity@v7
          with:
            singularity-version: 3.8.3
        - name: Build a singularity container
          run: singularity build --fakeroot fqw.sif Singularity.def
        - name: Test the singularity container
          run: singularity run fqw.sif help
        # - uses: actions/upload-artifact@v3
        #   with:
        #     name: fqwsif-artifact.sif
        #     path: fqw.sif
        - name: Push artifacts to Library
          run: |
            SYLABS-TOKEN="${{ secrets.sylabs_token }}"
            echo "TOKEN: $SYLABS-TOKEN"
            singularity remote login --username mazzalab
            singularity push fqw.sif library://mazzalab/fastqwiper/fqw.sif:${{ inputs.package_version }}